//! Precompiled ISA Programs
//!
//! This module contains ISA Programs that are precompiled at build-time from Python kernel schemas.
//! Programs are generated by `hologram-core/build.rs` and embedded as `pub const` declarations.
//!
//! ## Build-Time Compilation Pipeline
//!
//! ```text
//! Python Kernel Schemas (.py)
//!     ↓ [atlas_compile.py]
//! JSON Schemas (.json in target/json/)
//!     ↓ [hologram-core/build.rs: translate_json_to_isa()]
//! ISA Programs
//!     ↓ [serialize_program()]
//! Rust const code (OUT_DIR/precompiled_ops.rs)
//!     ↓ [include! macro]
//! This module: pub const VECTOR_ADD_F32: Program
//! ```
//!
//! ## Usage
//!
//! Operations reference precompiled Programs directly (zero overhead):
//!
//! ```rust,no_run
//! use hologram_core::precompiled_programs;
//! use hologram_core::Result;
//!
//! pub fn vector_add(/* params */) -> Result<()> {
//!     // Direct const reference (no allocation, no lookup)
//!     let program = &precompiled_programs::ADD;
//!
//!     // Execute precompiled program
//!     // exec.backend.execute_program(program, &config)?;
//!     Ok(())
//! }
//! ```
//!
//! ## Available Programs
//!
//! Programs are named with the pattern `{OPERATION}_{TYPE}`:
//! - `VECTOR_ADD_F32`, `VECTOR_ADD_F64`, `VECTOR_ADD_I32`, etc.
//! - `SIGMOID_F32`, `TANH_F32`, `RELU_F32`, etc.
//! - `SIN_F32`, `COS_F32`, `EXP_F32`, `LOG_F32`, etc.
//!
//! ## Implementation Notes
//!
//! - Programs use `Address::RegisterIndirectComputed` for buffer addressing
//! - Buffer handles are passed via register initialization (R1, R2, R3)
//! - Element offsets computed from special registers (R255 = GLOBAL_LANE_ID)
//! - All Programs are fully precompiled - no runtime construction

// Include build-time generated precompiled programs
include!(concat!(env!("OUT_DIR"), "/precompiled_ops.rs"));
