### NOTE: This file has been moved to `.github/workflows/changelog.yml` to execute as a workflow in the monorepo layout.
### Keep this file only for reference or backward compatibility; the active workflow lives in `.github/workflows/`.
name: Update Changelog

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allow manual trigger

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for changelog generation
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog with git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose --output CHANGELOG.md
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet CHANGELOG.md; then
            echo "No changes to CHANGELOG.md"
            exit 0
          fi

          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG.md [skip ci]"
          git push
