//! Generated tests for auto-generated ONNX operators
//!
//! Uses existing test macros for consistency.
//! Generated by: scripts/generate_onnx_operators.py

#![allow(clippy::useless_vec)]

use super::*;
use hologram_onnx_compiler::hrm::ops::*;

test_operator_basic! {
    test_abs_basic,
    AbsOp,
    inputs: [vec![1.0, 2.0, 3.0, 4.0]],
    expected: vec![1.0, 2.0, 3.0, 4.0],
    tolerance: 1e-5
}

test_operator_basic! {
    test_neg_basic,
    NegOp,
    inputs: [vec![1.0, 2.0, 3.0, 4.0]],
    expected: vec![-1.0, -2.0, -3.0, -4.0],
    tolerance: 1e-5
}

test_operator_basic! {
    test_sqrt_basic,
    SqrtOp,
    inputs: [vec![1.0, 4.0, 9.0, 16.0]],
    expected: vec![1.0, 2.0, 3.0, 4.0],
    tolerance: 1e-5
}

#[test]
fn test_sin_basic() {
    setup_test!(SinOp => atlas, op);
    let input = vec![1.0, 2.0, 3.0, 4.0];
    let result = execute_op!(atlas, op, [&input]);
    // Transcendental function - just verify it executes without error
    assert_eq!(result.len(), input.len());
}

#[test]
fn test_cos_basic() {
    setup_test!(CosOp => atlas, op);
    let input = vec![1.0, 2.0, 3.0, 4.0];
    let result = execute_op!(atlas, op, [&input]);
    // Transcendental function - just verify it executes without error
    assert_eq!(result.len(), input.len());
}

#[test]
fn test_tan_basic() {
    setup_test!(TanOp => atlas, op);
    let input = vec![1.0, 2.0, 3.0, 4.0];
    let result = execute_op!(atlas, op, [&input]);
    // Transcendental function - just verify it executes without error
    assert_eq!(result.len(), input.len());
}
